#!/usr/bin/php

<?php

// argc - argv

class CLITaskApp {

    public $command;

    public function run($argv) {

        $this->setCommand($argv[1]);

        switch ($this->command) {
            case 'add':
                $this->add($argv[2]);
                break;
            case 'update':
                break;
            case 'delete':
                break;
            case 'mark-in-progress':
                break;
            case 'mark-done':
                break;
            case 'list':
                break;
            default:
                echo 'Unknown command: ' . $this->command;
        }
    }

    public function setCommand($command) {
        $this->command = $command;
    }

    public function createTask($id, $description, $status, $createdAt, $updatedAt)
    {
        return ['id' => $id, 'description' => $description, 'status' => $status, 'createdAt' => $createdAt, 'updatedAt' => $updatedAt];
    }

    public function add($description)
    {
        $tasks = file_get_contents('tasks.json');
        $tempTasks = json_decode($tasks, true);

        $id = 1;
        if (!empty($tempTasks)) {
            $id = max(array_column($tempTasks, 'id'));
            $id++;
        }

        $tempTasks[] = $this->createTask($id, $description, 'todo', date('Y-m-d H:i:s'), date('Y-m-d H:i:s'));
        file_put_contents('tasks.json', json_encode($tempTasks, JSON_PRETTY_PRINT));
    }
}

$app = new CLITaskApp();
$app->run($argv);
