#!/usr/bin/php

<?php
class CLITaskApp {

    public $command;
    public $tasks = array();

    public function __construct()
    {
        if (!file_exists('tasks.json')) {
            fopen('tasks.json', 'w');
        }

        $tasks = file_get_contents('tasks.json');
        $tasks = json_decode($tasks, true);

        $this->tasks = $tasks;
    }

    public function run($argv) {

        $this->setCommand($argv[1]);

        if (!isset($argv[2]) && $this->command !== 'list') {
            echo "ERROR: Provide an argument";
            return;
        }

        switch ($this->command) {
            case 'add':
                $this->add($argv[2]);
                break;
            case 'update':
                if (!isset($argv[3])) {
                    echo "ERROR: Provide a description";
                }
                $this->update((int) $argv[2], $argv[3]);
                break;
            case 'delete':
                $this->delete((int) $argv[2]);
                break;
            case 'mark-in-progress':
            case 'mark-done':
                $status = substr($this->command, strlen('mark-'));
                $this->update((int) $argv[2], $status, true);
                break;
            case 'list':
                if (!in_array($argv[2], ['todo', 'done', 'in-progress'])) {
                    echo "ERROR: " . $argv[2] . " is not a valid status";
                    return;
                }

                $this->listTasks($argv[2]);
                break;
            default:
                echo 'Unknown command: ' . $this->command;
        }
    }

    public function setCommand($command) {
        $this->command = $command;
    }

    public function createTask($id, $description, $status, $createdAt, $updatedAt)
    {
        return ['id' => $id, 'description' => $description, 'status' => $status, 'createdAt' => $createdAt, 'updatedAt' => $updatedAt];
    }

    public function save()
    {
        file_put_contents('tasks.json', json_encode($this->tasks, JSON_PRETTY_PRINT));
    }

    public function add($description)
    {
        $id = 0;
        if (!empty($this->tasks)) {
            $id = max(array_column($this->tasks, 'id'));
            $id++;
        }

        $this->tasks[] = $this->createTask($id, $description, 'todo', date('Y-m-d H:i:s'), date('Y-m-d H:i:s'));
        $this->save();

        echo "Task added succesfully (ID: " . $id . ")\n";
    }

    public function update($id, $description, $status = false)
    {
        foreach ($this->tasks as &$task) {
            if ($task['id'] === $id) {

                if ($status) {
                    $task['status'] = $description;
                } else {
                    $task['description'] = $description;
                }
            }
        }
        unset($task);
        $this->save();
    }

    public function delete($id)
    {
        foreach ($this->tasks as $key => $task) {
            if ($task['id'] === $id) {
               unset($this->tasks[$key]);
            }
        }

        $this->tasks = array_values($this->tasks);
        $this->save();
    }

    public function listTasks($status = null)
    {
        foreach ($this->tasks as $task) {
            if (!empty($status) && $status !== $task['status']) {
                continue;
            }
            echo $task['id'] . ' | ' . $task['status'] . ' | ' . $task['description'] . PHP_EOL;
        }
    }
}

$app = new CLITaskApp();
$app->run($argv);
